---
alias: Toilet - Input boolean - off

trigger:
  - platform: state
    entity_id: input_boolean.toilet_warm_light, input_boolean.toilet_white_light
    from: "on"
    to: "off"

condition:
  - condition: template
    value_template: >-
      {%- if trigger.entity_id == 'input_boolean.toilet_white_light' -%}
        {{ is_state('input_boolean.toilet_warm_light', 'off') }}
      {%- else -%}
        {{ is_state('input_boolean.toilet_white_light', 'off') }}
      {%- endif -%}

action:
  - service: light.turn_off
    entity_id: light.toilet
