---
alias: Toilet light - motion light

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_2
  from: "off"
  to: "on"

action:
  - service: light.turn_on
    target:
      entity_id: light.toilet

  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_2
      from: "on"
      to: "off"

  - delay: 60

  - service: light.turn_off
    target:
      entity_id: light.toilet