---
alias: Media players - Apple TV - Automatic Cinema Mode
description: "Turns on the Cinema Mode when the Apple TV has been playing for 30 seconds."
trigger:
  - platform: state
    entity_id: media_player.living_room
    to: playing
    for:
      seconds: 15

  - platform: state
    entity_id: media_player.living_room
    to: idle
    for:
      seconds: 15

condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: input_boolean.cinema_mode
    state: off
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: media_player.living_room
            state: playing
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.cinema_mode_on
    default:
      - service: script.turn_off
        target:
          entity_id: script.cinema_mode_off
mode: single
