---
id: "1615645760315"
alias: Stalker mode - start command
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/stalk"
condition: []
action:
  - service: telegram_bot.send_message
    data_template:
      target: !secret telegram_admin_id
      disable_notification: true
      message: |
        *Stalker mode will start in 10 seconds* 🕵️

        I will inform of *every change in the house*.

        You can stop the stalker mode with the command */stop_stalking*
      inline_keyboard:
        - Stop stalking 🚫:/stop_stalking
  - delay:
      seconds: 10
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.stalker_mode

mode: restart
