---
id: "1660645760316"
alias: Stalker mode - stop command
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/stop_stalking"
condition: []
action:
  - service: telegram_bot.send_message
    data:
      target: !secret telegram_admin_id
      data_template:
        message: >-
          Stalker mode stopped. 
          
          To start again use the command /stalk
      inline_keyboard:
        - Start stalker mode 🕵️:/stalk
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.stalker_mode
mode: restart
