---
id: "1675091559442"
alias: Stalker mode
trigger:
  platform: event
  event_type: state_changed
mode: parallel
max: 25
condition: 
  - condition: state
    entity_id: input_boolean.stalker_mode
    state: "on"
  - "{{ trigger.event.data.new_state.domain in ['light', 'switch', 'fan', 'binary_sensor', 'media_player'] }}"
action:
  - service: telegram_bot.send_message
    data:
      target: !secret telegram_admin_id
      message: "{{ state_attr(trigger.event.data.entity_id, 'friendly_name') }} changed to {{ trigger.event.data.new_state.state }}"
mode: single
