- id: '1642246828915'
  alias: Find my phone - Jorge
  trigger:
  - platform: state
    entity_id: input_button.jorge_find_my_phone
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.jorge_find_my_phone
  mode: single
- id: '1642246828916'
  alias: Find my phone - Marlyn
  trigger:
  - platform: state
    entity_id: input_button.marlyn_find_my_phone
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.marlyn_find_my_phone
  mode: single
- id: '1661349052368'
  alias: Toilet light - Door open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.toilet_door
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.toilet
  mode: single
- id: '1661350105564'
  alias: Toilet light - Motion activated light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.toilet_motion
      light_target:
        entity_id: light.toilet
      no_motion_wait: 300
- id: '1662193818087'
  alias: Find my phone - Jorge
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_ns_panel_person_2
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.kitchen_ns_panel_person_2
    to: 'on'
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.jorge_find_my_phone
  mode: single
- id: '1662193818088'
  alias: Find my phone - MG
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_ns_panel_person_1
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.kitchen_ns_panel_person_1
    to: 'on'
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.marlyn_find_my_phone
  mode: single
- id: '1639589269236'
  alias: Telegram helper - alert callback Jorge
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /alert_jorge
  action:
  - service: script.turn_on
    target:
      entity_id: script.jorge_find_my_phone
  - service: notify.group_telegram
    data:
      message: Ok, I'm ringing his phone
- id: '1639589269237'
  alias: Telegram helper - alert callback MG
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /alert_mg
  action:
  - service: script.turn_on
    target:
      entity_id: script.marlyn_find_my_phone
  - service: notify.group_telegram
    data:
      message: Ok, I'm ringing her phone
- id: '1665167162070'
  alias: Hallway - Automatic light on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.parking_door
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.entrance_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.hallway
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.entrance_motion
      to: 'off'
    - platform: state
      entity_id:
      - binary_sensor.front_door
      to: 'off'
    - platform: state
      entity_id:
      - binary_sensor.parking_door
      to: 'off'
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.hallway
  mode: single
- id: '1665436739497'
  alias: Third floor - Automatic light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.third_floor_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: time
    before: '23:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    after: 09:00:00
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.third_floor
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.third_floor_motion
      to: 'off'
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.third_floor
  mode: single
