- id: '1642246828915'
  alias: Find my phone - Jorge
  trigger:
  - platform: state
    entity_id: input_button.jorge_find_my_phone
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.jorge_find_my_phone
  mode: single
- id: '1642246828916'
  alias: Find my phone - Marlyn
  trigger:
  - platform: state
    entity_id: input_button.marlyn_find_my_phone
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.marlyn_find_my_phone
  mode: single
- id: '1661349052368'
  alias: Toilet light - Door open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.toilet_door
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.toilet
  mode: single
- id: '1661350105564'
  alias: Toilet light - Motion activated light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.toilet_motion
      light_target:
        entity_id: light.toilet
      no_motion_wait: 300
- id: '1661358388889'
  alias: Parking light - Nighttime light
  description: ''
  use_blueprint:
    path: homeassistant/nighttime_light.yaml
    input:
      target_light:
        entity_id: light.parking
