---
homeassistant:
  name: !secret home_name
  external_url: !secret external_url
  internal_url: !secret internal_url
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam

  packages: !include_dir_named integrations