default_config:

homeassistant:
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customizations

sensor: !include_dir_list entities/sensors

script: !include_dir_named scripts

scene: !include scenes.yaml

scene split: !include_dir_list scenes