---
id: "1661671572968"
alias: Outdoor lights - Nighttime
trigger:
  - platform: state
    entity_id:
      - binary_sensor.night
condition: []
action:
  - if:
      - condition: state
        entity_id: binary_sensor.night
        state: "off"
    then:
      - service: light.turn_off
        target:
          entity_id: light.outdoor
    else:
      - service: light.turn_on
        target:
          entity_id: light.outdoor
mode: single
