id: "1667743895400"
alias: Scene - Sunset
trigger:
  - platform: state
    entity_id:
      - sun.sun
    to: below_horizon
action:
  - service: scene.turn_on
    target:
      entity_id: scene.sunset
mode: single
