---
alias: Notification - Dryer - Finished

trigger:
  platform: state
  entity_id: input_boolean.dryer
  to: "off"
action:
  - service: notify.group_telegram
    data_template:
      message: >
        {{ [
          "Hello!",
          "Hi!",
          "Hola!",
        ] | random}}
        {{ "*The dryer has finished!*" }}
        {{ [
          "you can pick up your clothes now 🧦👙👖",
          "I know, folding clothes is the worst 🥲",
          "Don't leave those clothes there for ages 😅",
          "🥲",
          ] | random }}
