---
id: "28155638615857"
alias: Notification - Washing machine - Finished

trigger:
  platform: state
  entity_id: input_boolean.washing_machine
  to: "off"
action:
  - service: notify.group_telegram
    data_template:
      message: >
        {{ [
          "Hello!",
          "Hi!",
          "Hoi!",
          "Hola!",
        ] | random}}
        {{ "*The washing machine has finished!*" }}
        {{ [
          "Time to dry them 🌀",
          "Don't leave those clothes there for ages 😅",
          "🙄",
          ] | random }}
