alias: conditional_media_all_off
id: "6882931899148"
initial_state: true
trigger:
  - platform: template
    value_template: >
      {{ is_state('media_player.living_room', 'idle') and
      is_state('media_player.spotify', 'idle')
      or
      is_state('media_player.philps', 'off') }}
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.conditional_media
      option: Recently added
