---
alias: Conditional media - Playing
id: '5557842567134'
initial_state: true
mode: restart
trigger:
  - platform: state
    entity_id:
      - media_player.living_room
      - media_player.spotify
    to: playing
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.conditional_media
      option: >
        {{ trigger.to_state.name }}