platform: homeassistant
id: temperature_1d
entity_id: sensor.temperature_1d
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("WeatherDetails.high_1d", "%s", id(temperature_1d).state.c_str());
