platform: homeassistant
id: temperature_2d
entity_id: sensor.temperature_2d
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("WeatherDetails.high_2d", "%s", id(temperature_2d).state.c_str());
