---
id: "1665167162071"
alias: Kitchen - Automatic light on
trigger:
  - platform: state
    entity_id:
      - binary_sensor.kitchen_door
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.kitchen_motion
    to: "on"
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_motion
        to: "off"
      - platform: state
        entity_id:
          - binary_sensor.kitchen_door
        to: "off"
  - delay:
      hours: 1
  - service: light.turn_off
    target:
      entity_id: light.kitchen
mode: restart
