---
alias: Telegram Assistant - Are you playing?

trigger:
  - platform: event
    event_type: telegram_text

condition:
  - condition: template
    value_template: '{{trigger.event.data.text|regex_match("(.*)(est(.)n?s? jugando)(.*)\?|(.*)(are you playing)\?",ignorecase=TRUE) }}'

action:
  - service: telegram_bot.send_message
    data_template:
      target: "{{ trigger.event.data.chat_id }}"
      message: >
        {% if states('media_player.ps4') | lower == 'playing' %}
          Yeap! the PS4 in the living room is on
        {% else %}
          Nope! the PS4 in the living room is off.
        {% endif %}
