---
blueprint:
  name: Automatic light
  description: >
    This automation will turn on the target light on based on a series of conditions.
    For example:
      - There's motion between a set time and day combination
      - The cinema mode is on
      - The light of the kitchen or the living room is on

    It will turn off the light when there's no more motion for X seconds.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entity:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    data_white:
      name: Data for the white light
    data_warm:
      name: Data for the warm light

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: 'off'
    to: 'on'
condition: [ ]
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: 09:00
                before: '20:00'
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
              - condition: time
                after: '10:00'
                before: '20:00'
                weekday:
                  - sat
                  - sun
        sequence:
          - service: light.turn_on
            data: !input data_white
            entity_id: !input light_entity
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: '20:00'
                before: '23:00'
              - condition: state
                entity_id: light.kitchen
                state: 'on'
              - condition: state
                entity_id: light.living_room
                state: 'on'
        sequence:
          - service: light.turn_on
            data: !input data_warm
            entity_id: !input light_entity
    default: [ ]
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        from: 'on'
        to: 'off'
  - delay: !input no_motion_wait
  - service: light.turn_off
    entity_id: !input light_entity
    data:
      transition: 1
mode: restart