---
blueprint:
  name: Turn on light and its relative input boolean based on an event
  description: >
    A blueprint that turns on the selected light when an event occurs.

  domain: automation

  input:
    event_type:
      name: Event type
    event_data:
      name: Event data
    light_entity:
      name: Light entity ID
    input_boolean:
      name: Input boolean
    data:
      name: Data

trigger:
  - platform: event
    event_type: !input event_type
    event_data: !input event_data
  - platform: state
    entity_id: !input input_boolean
    from: 'off'
    to: 'on'

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data: !input data
  - service: input_boolean.turn_on
    target:
      entity_id: !input input_boolean