---
blueprint:
  name: Sync input boolean - off
  description: >
    Syncs the input boolean when the lights goes off

  domain: automation

  input:
    light_entity:
      name: Light entity ID
    white_input_boolean:
      name: White input boolean
    warm_input_boolean:
      name: Warm input boolean

trigger:
  - platform: state
    entity_id: !input light_entity
    from: 'on'
    to: 'off'
condition: [ ]
action:
  - service: input_boolean.turn_off
    data: { }
    entity_id: !input warm_input_boolean
  - service: input_boolean.turn_off
    data: { }
    entity_id: !input white_input_boolean
mode: single