---
blueprint:
  name: Turn on a target light. With color based on the position of the sun.
  description: >
    A blueprint that turns on the selected light when an event occurs.
    The light will be warm, when the sun is below horizon and white if not

  domain: automation

  input:
    event_type:
      name: Event type
    event_data:
      name: Event data
    white_light_entity:
      name: White light entity
    warm_light_entity:
      name: Warm light entity

trigger:
  - platform: event
    event_type: !input event_type
    event_data: !input event_data

condition:
  - condition: state
    entity_id: !input light_entity
    state: "off"

action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: time
                after: '11:00'
              - condition: state
                entity_id: sun.sun
                state: "above_horizon"
        sequence:
          - service: light.turn_on
            entity_id: !input white_light_entity
    default:
      - service: light.turn_on
        entity_id: !input warm_light_entity
