---
blueprint:
  name: Turn on a target light. With color based on the position of the sun.
  description: >
    A blueprint that turns on the selected light when an event occurs.
    The light will be warm, when the sun is below horizon and white if not

  domain: automation

  input:
    event_type:
      name: Event type
    click_type:
      name: Click type
    switch_entity:
      name: Switch entity ID
    light_target:
      name: Light entity ID

trigger:
  - platform: event
    event_type: !input event_type
    event_data:
      entity_id: !input switch_entity
      click_type: !input click_type

condition:
  - condition: state
    entity_id: !input light_target
    state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input light_target
            state: "off"
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
              data: !include ../../../general_utilities/lights/white_light.yaml
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_target
          data: !include ../../../general_utilities/lights/yellow_light.yaml
