---
blueprint:
  name: Turn on light based on an event
  description: >
    A blueprint that turns on the selected light when an event occurs.

  domain: automation

  input:
    event_type:
      name: Event type
    event_data:
      name: Event data
    light_entity:
      name: Light entity ID
    data:
      name: Data

trigger:
  - platform: event
    event_type: !input event_type
    event_data: !input event_data

condition:
  - condition: state
    entity_id: !input light_entity
    state: "off"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data: !input data
