---
blueprint:
  name: Turn on a target light. With color based on the position of the sun.
  description: >
    A blueprint that turns on the selected light when an event occurs.
    The light will be warm, when the sun is below horizon and white if not

  domain: automation

  input:
    event_type:
      name: Event type
    event_data:
      name: Event data
    light_entity:
      name: Light entity ID
    data_white:
      name: Data for the white light
    data_warm:
      name: Data for the warm light

trigger:
  - platform: event
    event_type: !input event_type
    event_data: !input event_data

condition:
  - condition: state
    entity_id: !input light_entity
    state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: "above_horizon"
        sequence:
          - service: light.turn_on
            entity_id: !input light_entity
            data: !input data_white
    default:
      - service: light.turn_on
        entity_id: !input light_entity
        data: !input data_warm
