---
blueprint:
  name: Turn off light based on an event
  description: >
    A blueprint that turns off the selected light when an event occurs

  domain: automation

  input:
    event_type:
      name: Event type
    click_type:
      name: Click type
    switch_entity:
      name: Switch entity ID
    light_target:
      name: Light entity ID

trigger:
  - platform: event
    event_type: !input event_type
    event_data:
      entity_id: !input switch_entity
      click_type: !input click_type

condition:
  - condition: state
    entity_id: !input light_target
    state: "on"

action:
  - service: light.turn_off
    target:
      entity_id: !input light_target
