---
blueprint:
  name: Turn on light based on an event
  description: >
    A blueprint that turns on the selected light when an event occurs.
    The light will be always white

  domain: automation

  input:
    event_type:
      name: Event type
    click_type:
      name: Click type
    switch_entity_id:
      name: Switch entity ID
    light_entity_id:
      name: Light entity ID

trigger:
  - platform: event
    event_type: !input event_type
    event_data:
      entity_id: !input switch_entity_id
      click_type: !input click_type

condition:
  - condition: state
    entity_id: !input light_entity_id
    state: "off"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity_id
    data: !include ../../../general_utilities/lights/white_light.yaml