---
blueprint:
  name: Turn off light based on an event
  description: >
    A blueprint that turns off the selected light when an event occurs

  domain: automation

  input:
    event_type:
      name: Event type
    event_data:
      name: Event data
    light_target:
      name: Light entity ID

trigger:
  - platform: event
    event_type: !input event_type
    event_data: !input event_data

condition:
  - condition: state
    entity_id: !input light_target
    state: "on"

action:
  - service: light.turn_off
    target:
      entity_id: !input light_target
