---
id: "1674168897049"
alias: Front door doorbell - pause motion detection
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.front_door
    to: "on"
  - platform: state
    entity_id:
      - person.jorge
    to: home
  - platform: state
    entity_id:
      - person.marlyn
    to: home
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.front_door_motion_detection
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
        to: "off"
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.front_door_motion_detection
mode: restart