---
id: "1639494918295"
alias: Christmas tree - Fixed time turn off
description: "Turns off the Christmass tree at a fixed time"
trigger:
  - platform: time
    at: 01:00:00
action:
  - service: light.turn_off
    target:
      entity_id: light.christmas_tree
mode: single
