---
alias: Bedroom - Input boolean - Turn off

trigger:
  - platform: state
    entity_id: light.bedroom
    from: "on"
    to: "off"

action:
  - service: light.turn_off
    entity_id: light.bedroom_warm_light, light.bedroom_white_light