---
id: "1639589269236"
alias: Telegram helper - alert callback Jorge
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: /alert_jorge
action:
  - service: script.find_my_phone
    data:
      service: !secret notify_jorges_iphone
  - service: notify.group_telegram
    data:
      message: Ok, I'm ringing his phone
