addressable_lambda:
  name: Blue Scan
  update_interval: 25ms
  lambda: static int step = 0;
    static int direction = 1;

    if(initial_run){
      step = 0;
    }


    it[step] = ESPColor(0,0,255);
    
    if(step >0 && step < it.size()){
      it[step + (direction * -1)] = ESPColor::BLACK;
    }

    step = step + direction;

    if(step >= it.size() || step < 0){
      direction = direction * -1;
      step = step + (direction * 2);
    }
