addressable_lambda:
  name: Candy Cane
  update_interval: 100ms
  lambda: static int state = 0;
    const int width = 16;

    for (int i = it.size() - 1; i > 0; i--) {
    it[i] = it[i - 1].get();
    }

    if(state < width/2){
    it[0] = ESPColor(255,0,0);
    } else {
    it[0] = ESPColor::WHITE;
    }

    state += 1;
    if (state >= width)
    state = 0;
