# Temperature outside, fetched from HA
platform: homeassistant
id: temp_outdoor
entity_id: sensor.buienradar_temperature_feels_like
attribute: temperature_source_value
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("Home.temp", "%.0f", id(temp_outdoor).state);
