---
alias: Living room light - Input boolean - on

trigger:
  - platform: state
    entity_id: input_boolean.living_room_warm_light, input_boolean.living_room_white_light
    from: "off"
    to: "on"
action:
  - service: input_boolean.turn_off
    data_template:
      entity_id: >
        {% set booleans = [ 'input_boolean.living_room_warm_light', 'input_boolean.living_room_white_light' ] | reject('equalto', trigger.entity_id) | list %}
        {{ booleans[0] }}
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.entity_id == "input_boolean.living_room_white_light" }}'
        sequence:
          - service: light.turn_on
            entity_id: light.living_room
            data: !include /config/general_utilities/lights/white_light.yaml
    default:
      - service: light.turn_on
        entity_id: light.living_room
        data: !include /config/general_utilities/lights/warm_light.yaml
