id: "1639589269235"
alias: "Telegram helper - alert"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: "/alert"
action:
  - service: telegram_bot.send_message
    data:
      message: "Who do you want to alert?"
      target: !secret telegram_group_id
      inline_keyboard:
        - "Jorge:/alert_jorge, MG:/alert_mg"
