---
id: '1639589269237'
alias: Telegram helper - alert callback MG
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: /alert_mg
action:
- service: script.turn_on
  target:
    entity_id: script.marlyn_find_my_phone
- service: notify.group_telegram
  data:
    message: Ok, I'm ringing her phone