---
id: "1639489269700"
alias: Garbage pick-up notification
description: "Notifies when HVC will pick the trash containers"
trigger:
  - platform: time
    at: "20:00:00"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.hvc_groep_gft
        state: Morgen
        attribute: day
      - condition: state
        entity_id: sensor.hvc_groep_papier
        state: Morgen
      - condition: state
        entity_id: sensor.hvc_groep_plastic
        state: Morgen
        attribute: day
action:
  - service: notify.group_telegram
    data_template:
      message: >
        {{ [
          "Hello!",
          "Hi!",
          "Hoi!",
          "Hola!",
        ] | random}}
        {{ "*Tomorrow, they will pick-up the trash.*" }}

        {% if is_state_attr('sensor.hvc_groep_gft', 'day', 'Morgen') %}{{ "They will pick-up GTF (the green container 🟢) "}}{% endif %}
        {% if is_state_attr('sensor.hvc_groep_papier', 'day', 'Morgen') %}{{ "They will pick-up paper (the blue container 🔵) "}}{% endif %}
        {% if is_state_attr('sensor.hvc_groep_plastic', 'day', 'Morgen') %}{{ "They will take plastic (the orange container 🟠) "}}{% endif %}
mode: single
