---
id: "1639494841193"
alias: Outdoor lighting - Sunset turn on
description: "Turns the outdoor lightning on when the sun goes below horizon"
trigger:
  - platform: state
    entity_id: sun.sun
    to: below_horizon
action:
  - service: light.turn_on
    target:
      entity_id: light.decorative_outdoor
    data:
      brightness_pct: 30
      transition: 1
