---
id: '29931871079410'
alias: Shower light - Automatic light
description: >
  This automation will turn on the shower light on based on a series of conditions.
  For example:
    - There's motion between a set time and day combination
    - The light of the kitchen or the living room is on

  It will turn off the light when there's no more motion for 360 seconds

trigger:
  - platform: state
    entity_id: group.shower_sensors
    from: "off"
    to: "on"
condition: []
action:
  - service: light.turn_on
    entity_id: light.shower
    data: !include /config/general_utilities/lights/slow_white_light.yaml
  - wait_for_trigger:
      - platform: state
        entity_id: group.shower_sensors
        from: "on"
        to: "off"
    continue_on_timeout: false
  - delay: 360
  - service: light.turn_off
    data:
      transition: 1
    entity_id: light.shower
mode: restart
