id: "1686153484964"
alias: Shopping list - Action - Marlyn
trigger:
  - platform: zone
    entity_id: person.marlyn
    zone: zone.action
    event: enter
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.action_shopping_list_count
        above: 0
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: zone.action
            attribute: persons
            below: 2 # means we are together and we don't want to export twice
          - condition: numeric_state
            entity_id: zone.action_2
            attribute: persons
            below: 2 # means we are together and we don't want to export twice
action:
  - service: shopping_list_splitter.export
  - service: shopping_list_splitter.import
    data:
      list_name: action
  - service: notify.mobile_app_marlyns_iphone
    data:
      data:
        actions:
          - clickAction: /shopping-list
            url: /shopping-list
      message: Cick here to open the Action shopping list
      title: Shopping list
mode: single
