id: "16861234457242"
alias: Shopping list - Supermarket - Jorge
trigger:
  - platform: zone
    entity_id: person.jorge
    zone: zone.supermarket
    event: enter
  - platform: zone
    entity_id: person.jorge
    zone: zone.supermarket_2
    event: enter
condition: []
action:
  - service: shopping_list_splitter.export
  - service: shopping_list_splitter.import
    data:
      list_name: supermarket
  - service: !secret notify_jorges_iphone
    data:
      data:
        actions:
          - clickAction: /shopping-list
            url: /shopping-list
      message: Cick here to open the shopping list
      title: Shopping list
mode: single
