id: "168615245722332"
alias: Shopping list - Reset
trigger:
  - platform: zone
    entity_id: person.jorge
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: person.marlyn
    zone: zone.home
    event: enter
condition: []
action:
  - service: shopping_list_splitter.import
