---
alias: System notification - Update available
trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    above: 0
action:
  - service: notify.admin_telegram
    data:
      message: 'There are HACS updates available.'