---
alias: System notification - Home Assistant restarted
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.group_system_notifications
    state: "on"
action:
  - service: notify.group_telegram
    data:
      message: "Home Assistant *is back online*! Everything should be working normally now."
