---
alias: System notification - Home Assistant shutting down
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.group_telegram
    data:
      message: "Home Assistant is restarting. Lights and automations *won't* work for a moment..."