---
id: '95532824989760'
alias: System notification - Low battery entities
trigger:
  - platform: time
    at: "10:00:00"
condition:
  condition: template
  value_template: "{% if states('sensor.low_battery') %}true{% endif %}"
action:
  - service: notify.admin_telegram
    data_template:
      message: >
        {%- set entities = states('sensor.low_battery').split(',') -%}
        {%- for entity in entities -%}
        - {{entity}}{{ '\n' -}}
        {%- endfor -%}
