---
id: '27714014329885'
alias: System notification - Update available
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: "off"
    to: "on"
action:
  - service: notify.admin_telegram
    data:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
