---
alias: System notification - Update available
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
action:
  - service: notify.admin_telegram
    data:
      message: 'There is a new Home Assistant release available.'