---
sensor:
  - unique_id: sidebar
    state: template
    attributes:
      time: |
        {%- set hours = '<span>' + now().strftime('%H') + '<span>' %}
        {%- set minutes = '</span>' + now().strftime('%M') + '</span>' %}
        <p>{{ hours }}:{{ minutes }}</p>
      date: |
        <font color='#6a7377'><b>
        {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != null %}
        {%- set days = ['Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag', 'Söndag'] %}
        {%- set months = ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni',
        'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'] %}
          {{- days[now().weekday()] }}<br>
          {{- strptime(states('sensor.date'), '%Y-%m-%d').day }} {{ months[now().month-1] }}
        {%- endif -%}
        </b></font>
      greet: |
        <b>
        {%- set time = now().hour %}
        {%- if time <= 1 -%} Good night {{'\U0001F611'}}
        {%- elif time <= 3 -%} Good night {{'\U0001F62A'}}
        {%- elif time <= 5 -%} Good night {{'\U0001F634'}}
        {%- elif time <= 7 -%} Good morning {{'\U0001F4A9'}}
        {%- elif time <= 9 -%} Good morning {{'\u2615\uFE0F'}}
        {%- elif time <= 10 -%} Good morning {{'\U0001F642'}}
        {%- elif time <= 13 -%} Good afternoon {{'\U0001F60A'}}
        {%- elif time <= 15 -%} Good afternoon {{'\U0001F60E'}}
        {%- elif time <= 17 -%} Good afternoon {{'\U0001F44B\U0001F3FB'}}
        {%- elif time <= 19 -%} Good evening {{'\U0001F44B\U0001F3FB'}}
        {%- elif time <= 22 -%} Good evening {{'\U0001F60C'}}
        {%- elif time <= 23 -%} Good evening {{'\U0001F974'}}
        {%- else %} Good evening {{'\U0001F974'}}
        {%- endif -%}
        </b>
      active: |
        <b>
        {%- set lights = [
          states.light.tv,
          states.light.golv,
          states.light.horna,
          states.light.dator,
          states.light.vask_hoger,
          states.light.vask_vanster,
          states.light.byra,
          states.light.garderob,
          states.light.hall_1,
          states.light.hall_2,
          states.light.hall_3,
          states.light.mattias,
          states.light.sanja,
          states.light.spot_1,
          states.light.spot_2,
          states.switch.balkong
        ] %}
        {%- set switches = [
          states.switch.computer_imac,
          states.switch.tv_sony,
          states.switch.tv_samsung,
          states.switch.playstation_5,
          states.switch.wemo_monitors,
          states.fan.studio_wemo,
          states.fan.sovrum_anslut,
          states.fan.air_purifier
        ] %}
        {%- set lights_on = lights | selectattr('state','eq','on') | list %}
        {%- set lights_name = lights | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        {%- set switches_on = switches | selectattr('state','eq','on') | list %}
        {%- set switches_name = switches | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        {%- if (lights_on | length == 0) and (switches_on | length > 0) -%}
          {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} är på
        {%- elif (lights_on | length == 1) and (switches_on | length == 1) -%}
          {{ lights_name }} och {{switches_name }} är på
        {%- elif (lights_on | length == 1) and (switches_on | length > 1) -%}
          {{ lights_name }}, {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} är på
        {%- elif (lights_on | length > 1) and (switches_on | length == 1) -%}
          {{ lights_on | length }} lampor och {{ switches_name }} är på
        {%- elif (lights_on | length > 1) and (switches_on | length > 1) -%}
          {{ lights_on | length }} lampor, {{ switches_name | regex_replace(',([^,]*)$',' och\\1') }} är på
        {%- elif (lights_on | length == 1) and (switches_on | length == 0) -%}
          {{ lights_name }} är på
        {%- elif (lights_on | length > 1) and (switches_on | length == 0) -%}
          {{ lights_on | length }} lampor är på
        {%- else %}
          <font color='#6a7377'>Everything is off</font>
        {%- endif -%}
        </b>
      weather: |
        {%- set temperature = states('sensor.br_temperature') %}
        {%- set apparent = states('sensor.br_feel_temperature') | round %}
        {%- set precip = states('sensor.br_rain_1d') | round %}
        {% if not is_state('sensor.br_temperature', 'unknown') %}
          {%- if temperature | float <= 0.0 -%}
            Feels like {{ apparent }}° with {{ precip }}% chance of snow {{'\u2744\uFE0F'}}
          {%- elif temperature | float > 0.0 -%}
            Feels like {{ apparent}}° with {{ precip }}% chance of rain {{ '\u2614\uFE0F' if precip > 30 }}
          {%- endif %}
        {%- else %}
          Weather information not available
        {%- endif %}
      transport: |
        {% set entity_id = 'sensor.skanetrafiken' %}
        {% if states(entity_id) != 'unknown' %}
        {%- set date = strptime(state_attr(entity_id, 'date') + ' ' + state_attr(entity_id, 'time'), "%X") %}
        {%- set time = as_timestamp(date) | timestamp_custom('%H:%M') -%}
          Nästa buss går {{ time }} från {{ state_attr(entity_id, 'name').split()[1] }}
        {% endif %}