---
id: '1618841613229'
alias: Bedroom nightstand light - bedtime lighting

trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_2
      click_type: single
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: light.bedroom
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
action:
  - service: light.turn_off
    target:
      entity_id: light.bedroom
  - service: light.turn_on
    target:
      entity_id: light.e14_filament_2
mode: single