---
id: '3749991425673'
alias: Bedroom nightstand light - Toggles

trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_2
      click_type: single

action:
  - service: light.toggle
    target:
      entity_id: light.e14_filament_2