platform: homeassistant
id: homeassistant_time
on_time:
  - seconds: 0
    minutes: /1
    then:
      - lambda: id(disp1).set_component_text_printf("Home.time", "%02i:%02i", id(homeassistant_time).now().hour, id(homeassistant_time).now().minute);
      - lambda: id(disp1).set_component_text_printf("Home.date","%s", id(homeassistant_time).now().strftime("%a. %d %b").c_str());
on_time_sync:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("Home.time", "%02i:%02i", id(homeassistant_time).now().hour, id(homeassistant_time).now().minute);
    - lambda: id(disp1).set_component_text_printf("Home.date","%s", id(homeassistant_time).now().strftime("%a. %d %b").c_str());
