platform: template
name: $device_name Go to home
id: disp1_disgth
assumed_state: on
optimistic: true
on_turn_on:
  - lambda: id(disp1).send_command_printf("Home.disgth.val=0");
on_turn_off:
  - lambda: id(disp1).send_command_printf("Home.disgth.val=1");
