---
alias: Small bedroom input boolean - Turn off

description: Turns off the input booleans

trigger:
  - platform: state
    entity_id: light.kitchen
    from: 'on'
    to: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.kitchen_warm_light
  - service: input_boolean.turn_off
    entity_id: input_boolean.kitchen_white_light
mode: single