alias: Kitchen light - Turn on - white light
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_3_left
      click_type: single

condition:
  - condition: state
    entity_id: light.kitchen
    state: "off"
  - condition: 

action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen
    data: !include ../../../general_utilities/lights/warm_light.yaml