id: "1661676577238"
alias: Bruno Brushed - Reset
trigger:
  - platform: time
    at: "09:00:00"
condition: []
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.bruno_brushed
mode: single
