platform: nextion
name: $device_name Person 2 Details
page_id: 0
component_id: 14
on_click:
  - lambda: id(disp1).send_command_printf("PersonDetails.person_profile.pic=%i", 31);
  - lambda: id(disp1).set_component_text_printf("PersonDetails.location", "%s", id(person_2).state.c_str());
  - lambda: id(disp1).set_component_text_printf("PersonDetails.person_name","Jorge");
  - lambda: id(disp1).set_component_text_printf("PersonDetails.last_changed", "%s ago", id(person_2_time).state.c_str());
  - switch.template.publish:
      id: popup_person_1
      state: off
  - lambda: id(disp1).send_command_printf("page 3");
