---
id: "1668191360129"
alias: Backdoor - Motion detection
description: Pauses motion detection when the door is open
trigger:
  - platform: state
    entity_id:
      - binary_sensor.backdoor
    to: "on"
condition: []
action:
  - service: script.pause_doorbell_motion_sensor
    data:
      target: switch.backdoor_motion_detection
      trigger: binary_sensor.backdoor
      trigger_state: off
mode: restart
