---
id: "40065332104243"
alias: Backup - Weekly
initial_state: on
trigger:
  platform: time
  at: "18:00:00"
condition:
  condition: time
  weekday:
    - mon
action:
  - service: hassio.backup_full
    data_template:
      name: Automated backup - {{now().strftime('%Y%m%d%H%M%S')}}
  - delay:
      minutes: 30
  - service: hassio.addon_stdin
    data_template:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
  - service: input_boolean.turn_off
