---
id: "1668191360131"
alias: Backdoor - Door open - Motion detection
trigger:
  - platform: state
    entity_id:
      - binary_sensor.backdoor
    to: "on"
condition: []
action:
  - service: script.pause_doorbell_motion_sensor
    data:
      target: switch.backdoor_motion_detection
      wait_template: "{{ is_state('binary_sensor.backdoor', 'off') }}"
      delay: "00:30:00"
mode: restart
