---
alias: daily_backup.yaml
description: >-
  A full snapshot will be taken daily and stored on Dropbox.
initial_state: "on"
trigger:
  platform: time
  at: "04:00:00"
action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated backup - {{now().strftime('%Y%m%d%H%M%S')}}
  - delay:
      minutes: 30
  - service: hassio.addon_stdin
    data_template:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
  - service: input_boolean.turn_off
# test commit