---
id: "1668191360130"
alias: Front door - Motion detection
description: Pauses motion detection when the door is open
trigger:
  - platform: state
    entity_id:
      - binary_sensor.front_door
    to: "on"
condition: []
action:
  - service: script.pause_doorbell_motion_sensor
    data:
      target: switch.front_door_motion_detection
      wait_template: "{{ is_state('binary_sensor.front_door', 'off') }}"
      delay: "00:30:00"
mode: restart
