---
id: "1662193818088"
alias: Find my phone - MG
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bathroom_ns_panel_person_1
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.kitchen_ns_panel_person_1
    to: "on"
condition: []
action:
  - service: script.find_phone
    data:
      service: !secret notify_marlyns_iphone
mode: single
