---
id: "1665436739497"
alias: Third floor - Automatic light
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.third_floor_motion
    to: "on"
condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: time
    before: "22:00:00"
    after: 09:00:00
action:
  - service: light.turn_on
    target:
      entity_id: light.third_floor
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.third_floor_motion
        to: "off"
  - delay:
      minutes: 10
  - service: light.turn_off
    target:
      entity_id: light.third_floor
mode: restart
