---
id: '40065332104243'
alias: Backup - Weekly
description: >-
  A full backup will be taken weekly and stored on Dropbox.
initial_state: on
trigger:
  platform: time
  at: "18:00:00"
condition:
  condition: time
  weekday:
  - mon
action:
  - service: hassio.backup_full
    data_template:
      name: Automated backup - {{now().strftime('%Y%m%d%H%M%S')}}
  - delay:
      minutes: 30
  - service: hassio.addon_stdin
    data_template:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
  - service: input_boolean.turn_off