id: "1661676577236"
alias: Bruno Walked - Reset
trigger:
  - platform: time
    at: "09:00:00"
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "21:00:00"
condition: []
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.bruno_walked
mode: single
