---
id: "1660656599000"
alias: Brush Bruno - Done by button
trigger:
  - platform: device
    domain: mqtt
    device_id: bfe18abfcc6695d905bc68d61d22fea5
    type: click
    subtype: single
    discovery_id: 0x00158d00044ad328 click_single
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.brushed_bruno
mode: single
