---
id: "1660643921878"
alias: Brush Bruno - Trigger reminder
trigger:
  - platform: time_pattern
    hours: "1"
condition:
  - condition: state
    entity_id: input_boolean.bruno_brushed
    state: "off"
  - condition: time
    before: 00:00:00
    after: "18:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
action:
  - repeat:
      until:
        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.bruno_brushed
              state: "on"
            - condition: time
              before: 00:00:00
              after: "12:00:00"
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
                - sun
      sequence:
        - service: telegram_bot.send_message
          data:
            title: "*Important: Brush Bruno \U0001F436*"
            target: !secret telegram_group_id
            message:
              "{% set weekday = now().isoweekday() %} {% if weekday == 1 %}\n
              \ {% set target=\"Jorge\" %}\n{% elif weekday == 2 %}\n  {% set target=\"Marlyn\"
              %}\n{% elif weekday == 3 %}\n  {% set target=\"Jorge\" %}\n{% elif weekday
              == 4 %} {% set target=\"Marlyn\" %} {% elif weekday == 5 %}\n  {% set
              target=\"Jorge\" %}\n{% elif weekday == 6 %}\n {% set target=\"Marlyn\"
              %}\n{% elif weekday == 7 %}\n  {% set target=\"Jorge\" %}\n{%endif %}
              Hi *{{ target }}*! Please, remember to brush Bruno today\n"
            inline_keyboard:
              - I brushed him:/brush_bruno_done
        - delay:
            hours: 1
            minutes: 0
            seconds: 0
            milliseconds: 0
mode: single
