---
id: "1660640784016"
alias: Brush Bruno - reset at midnight
trigger:
  - platform: time
    at: "00:00:00"
condition: []
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.brushed_bruno
mode: single
