---
id: "1670329303436"
alias: Hallway light - Toggle
trigger:
  - platform: state
    entity_id:
      - sensor.wall_switch_1_action
    to: single
condition: []
action:
  - service: light.toggle
    target:
      entity_id: light.hallway
mode: single