id: "1642246828916"
alias: Find my phone - Marlyn
trigger:
  - platform: state
    entity_id: input_button.marlyn_find_my_phone
condition: []
action:
  - service: script.turn_on
    target:
      entity_id: script.marlyn_find_my_phone
mode: single
