---
id: "1675088799692"
alias: Bathroom - Automatic light
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bathroom_door
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.bathroom_motion
    to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: "off"
  - condition: state
    entity_id: light.bathroom
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
        - light.bathroom
        - light.bathroom_mirror
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.bathroom_motion
        to: "off"
  - delay:
      hours: 1
  - service: light.turn_off
    data: {}
    target:
      entity_id:
        - light.bathroom_mirror
        - light.bathroom
mode: restart
