---
id: "16621938180889"
alias: Find my phone - MG
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bathroom_ns_panel_person_1
    to: "on"
condition: []
action:
  - service: script.find_my_phone
    data:
      service: !secret notify_marlyns_iphone
mode: single
