---
id: "1676928551764"
alias: Mirror Light - Automatic on
trigger:
  - platform: state
    entity_id:
      - light.bathroom
    to: "on"
condition: []
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.bathroom_mirror
mode: single
