alias: Entrance light - automatic light
description: >
  This automation will turn on the entrance light on based on a series of conditions.
  For example:
    - There's motion between a set time and day combination
    - The cinema mode is on
    - The light of the kitchen or the living room is on
    - The door is open

  It will turn off the light when there's no more motion for 5 seconds and the door is closed

trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_1
    from: 'off'
    to: 'on'
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: sun
            before: sunrise
          - condition: time
            after: 09:00
            before: '23:59'
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      - condition: time
        after: '10:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
        before: '23:59'
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.cinema_mode
            state: 'on'
          - condition: time
            after: '10:00'
            before: 02:00
      - condition: or
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: light.living_room
            state: 'on'
      - condition: state
        entity_id: binary_sensor.door_sensor_1
        state: 'on'
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.cinema_mode
                state: 'on'
              - condition: time
                after: 00:00
                before: '10:00'
        sequence:
          - service: light.turn_on
            data: !include /config/general_utilities/lights/warm_light.yaml
            entity_id: light.entrance
    default:
      - service: light.turn_on
        data: !include /config/general_utilities/lights/white_light.yaml
        entity_id: light.entrance
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_1
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.door_sensor_1
        from: 'on'
        to: 'off'
  - service: light.turn_off
    data: { }
    entity_id: light.entrance
mode: restart
