---
alias: Entrance light - door triggered light

description: Turns on the entrance light when the door is opened
trigger:
  - platform: state
    entity_id: binary_sensor.door_sensor_1
    to: 'on'
condition: [ ]
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: '20:00'
                before: '10:00'
              - condition: state
                entity_id: light.kitchen
                state: 'on'
              - condition: state
                entity_id: light.living_room
                state: 'on'
        sequence:
          - service: light.turn_on
            data: !include /config/general_utilities/lights/warm_light.yaml
            entity_id: light.entrance
    default:
      - service: light.turn_on
        data: !include /config/general_utilities/lights/white_light.yaml
        entity_id: light.entrance
mode: single