---
id: "1675090243891"
alias: Air fresheners - Automatic toggling
trigger:
  - platform: time_pattern
    hours: /4
condition:
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: "off"
action:
  - service: switch.turn_on
    target:
      entity_id:
        - switch.entrance_air_freshener
        - switch.living_room_air_freshener
  - delay:
      hours: 2
  - service: switch.turn_off
    target:
      entity_id:
        - switch.entrance_air_freshener
        - switch.living_room_air_freshener
mode: single
