---
alias: Telegram Assistant - Weather brief by text

trigger:
  - platform: event
    event_type: telegram_text

condition:
  - condition: template
    value_template: '{{trigger.event.data.text|regex_match("(.*)(frio|llov|lluv|calor|nev|clima|temp|snow|rain|weather|tiempo)(.*)",ignorecase=TRUE) }}'

action:
  - service: notify.group_telegram
    data_template:
      message: >
        {{ states('sensor.brief') }}
