esphome:
  name: bedroom-wall-led-strip

esp8266:
  board: d1_mini
  framework:
    version: 2.7.4  

logger:
  level: ERROR

api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Bedroom-Wall-Led-Strip"
    password: !secret esphome_ap_password

captive_portal:
    
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 628
    rgb_order: GRB
    name: "Bedroom Wall Led Strip"
    effects: !include_dir_list light-effects