esphome:
  name: bedroom-tv-ambient-light
  on_boot:
    priority: -10
    then:
      - switch.turn_off: status_led

esp8266:
  board: d1_mini
  framework:
    version: recommended

logger:
  level: ERROR

api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "bedroom-tv-ambient-light"
    password: !secret esphome_ap_password

captive_portal:

switch:
  - platform: gpio
    pin: D4
    name: "Status LED"
    inverted: true
    id: status_led
    
light:
  - platform: neopixelbus
    variant: WS2812X
    pin: D3
    type: GRB
    num_leds: 170
    name: "Bedroom TV Ambient Light"
    effects: !include_dir_list light-effects