esphome:
  name: letter_j

esp8266:
  board: d1_mini
  framework:
    version: recommended

logger:
  level: ERROR

api:

ota:
  password: 5AxEst-k

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "letter_j"
    password: !secret esphome_ap_password

captive_portal:

light:
  - platform: monochromatic
    name: "Letter J"
    output: output_component1
    effects: !include_dir_list monochromatic-light-effects

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO2