esphome:
  name: pergola

esp8266:
  board: d1_mini
  framework:
    version: recommended

logger:
  level: ERROR

api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "pergola"
    password: !secret esphome_ap_password

captive_portal:

light:
  - platform: neopixelbus
    variant: WS2812X
    pin: D4
    type: GRB
    num_leds: 600
    name: "Pergola"
    effects: !include_dir_list light-effects