esphome:
  name: stairs

esp8266:
  board: d1_mini
  framework:
    version: 2.7.4  

logger:
  level: ERROR

api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Stairs"
    password: !secret esphome_ap_password

captive_portal:
    
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 504
    rgb_order: GRB
    name: "Stairs"
    effects: !include_dir_list light-effects

  - platform: fastled_clockless
    chipset: WS2812B
    pin: D3
    num_leds: 25
    rgb_order: GRB
    name: "Stairs plant"
    effects: !include_dir_list light-effects