esphome:
  name: stairs

esp8266:
  board: d1_mini
  framework:
    version: recommended

logger:
  level: ERROR

api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "stairs"
    password: !secret esphome_ap_password

captive_portal:

switch:
  - platform: gpio
    name: "Stairs photo frame"
    pin: GPIO4
light:
  - platform: neopixelbus
    variant: WS2812X
    pin: GPIO2
    type: GRB
    num_leds: 576
    name: "Stairs 1"
    effects: !include_dir_list light-effects
  - platform: neopixelbus
    variant: WS2812X
    pin: GPIO0
    type: GRB
    num_leds: 576
    name: "Stairs 2"
    effects: !include_dir_list light-effects