platform: homeassistant
id: condition
entity_id: sensor.buienradar_detailed_condition
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("Screensaver.condition", "%s", id(condition).state.c_str());
    - lambda: id(disp1).set_component_text_printf("Home.condition", "%s", id(condition).state.c_str());
