platform: homeassistant
id: entity_name
entity_id: light.hallway
attribute: friendly_name
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("Lights.entity_name_1", "%s", id(entity_name).state.c_str());
