platform: homeassistant
id: low_temperature_1d
entity_id: sensor.low_temperature_1d
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("WeatherDetails.low_1d", "%s", id(low_temperature_1d).state.c_str());
