platform: homeassistant
id: person_1
entity_id: person.marlyn
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: |-
        int symbol=21; // away symbol

        if (id(person_1).state == "home") {
          symbol=22;
          id(disp1).send_command_printf("Home.person_1_time.pco=%s", "14824");
          id(disp1).send_command_printf("Home.person_1_time.bco=%s", "54938"); 
        } else {
          id(disp1).send_command_printf("Home.person_1_time.bco=%s", "14824");
          id(disp1).send_command_printf("Home.person_1_time.pco=%s", "54938"); 
        }

        id(disp1).send_command_printf("Home.person_1.pic=%i", symbol);
