platform: homeassistant
id: person_1_time
entity_id: sensor.last_changed_marlyn
on_value:
  then:
    - wait_until:
        switch.is_on: nextion_init
    - lambda: id(disp1).set_component_text_printf("Home.person_1_time", "%s", id(person_1_time).state.c_str());
