---
id: "93422626026496"
alias: Dryer - Turn on the input boolean

trigger:
  platform: numeric_state
  entity_id: sensor.plug_1_current
  above: 0.1
  for:
    minutes: 1
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.dryer
  - service: input_datetime.set_datetime
    entity_id: input_datetime.dryer_start_time
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
mode: single
