---
id: "66556252950218"
alias: Dryer - Turn off the input boolean

trigger:
  platform: numeric_state
  entity_id: sensor.plug_1_current
  below: 0.1
  for:
    minutes: 1
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.dryer

  - service: logbook.log
    data:
      name: Dryer run time
      domain: input_datetime
      message: >
        The dryer ran for {{ states('sensor.dryer_time_on') }}

mode: single
