---
id: '93422666046451'
alias: Dryer - Turn on the input boolean

trigger:
  platform: numeric_state
  entity_id: sensor.plug_4_watts
  above: 0
  for:
    minutes: 2
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.dryer