---
id: '66556286250218'
alias: Dryer - Turn off the input boolean

trigger:
  platform: numeric_state
  entity_id: sensor.plug_1_watts
  below: 1
  for:
    minutes: 2
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.dryer