---
id: "1649329168234"
alias: Living room repellent - on
trigger:
  - platform: sun
    event: sunset
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.jorge
        state: home
      - condition: state
        entity_id: person.marlyn
        state: home
action:
  - service: switch.turn_on
    target:
      entity_id: switch.plug_5
mode: single
