---
id: "66574252952219"
alias: Washing machine - Time on

trigger:
  platform: time_pattern
  minutes: "*"

condition:
  condition: state
  entity_id: input_boolean.washing_machine
  state: "on"

action:
  service: homeassistant.update_entity
  entity_id: sensor.washing_machine_time_on

mode: single
