---
id: "93422626026451"
alias: Washing machine - Turn on the input boolean

trigger:
  platform: numeric_state
  entity_id: sensor.plug_2_power
  above: 4
  for:
    minutes: 5
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washing_machine
  - service: input_datetime.set_datetime
    entity_id: input_datetime.washing_machine_start_time
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
mode: single
