---
id: "93422626026451"
alias: Washing machine - Turn on the input boolean

trigger:
  platform: numeric_state
  entity_id: sensor.plug_2_current
  above: 0.1
  for:
    minutes: 1
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.washing_machine
mode: single
